# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_article', models.CharField(max_length=100, verbose_name='Title article')),
                ('description_article', models.TextField(verbose_name='Description')),
                ('create_article', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create data article')),
            ],
            options={
                'db_table': 'article_content',
            },
        ),
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cat', models.CharField(max_length=100, verbose_name='Name category')),
                ('description_cat', models.TextField(blank=True, default=None, null=True, verbose_name='Description category')),
                ('parent_cat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.CategoryArticle', verbose_name='Parent category')),
            ],
            options={
                'db_table': 'category_article',
            },
        ),
        migrations.CreateModel(
            name='CategoryCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cat', models.CharField(max_length=50, verbose_name='Name category')),
                ('short_desc_cat', models.CharField(max_length=200, verbose_name='Short description')),
                ('description_cat', models.TextField()),
                ('image_cat', models.ImageField(blank=True, default=None, null=True, upload_to='images/catalog_images')),
                ('parent_cat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.CategoryCatalog')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_man', models.CharField(max_length=100, verbose_name='Name manufacture')),
                ('site_man', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Site manufactures')),
            ],
            options={
                'db_table': 'manufactures',
            },
        ),
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(default=None, max_length=30, verbose_name='Name menu')),
                ('type_menu', models.CharField(choices=[('A', 'Articles category'), ('P', 'Products category')], default='A', max_length=1, verbose_name='Select type')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.NavbarMenu', verbose_name='Parent menu')),
            ],
            options={
                'db_table': 'navbar_nemu',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pro', models.CharField(max_length=150, verbose_name='Name product')),
                ('code_pro', models.CharField(max_length=50, verbose_name='Code product')),
                ('descriptions_pro', models.TextField(verbose_name='Description')),
                ('image_pro', models.ImageField(blank=True, default=None, null=True, upload_to='images/product_images')),
                ('category_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.CategoryCatalog', verbose_name='Category product')),
                ('manufactures_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Manufactures', verbose_name='Manufacture product')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.CategoryArticle', verbose_name='Category article'),
        ),
    ]
