# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='active_article',
            field=models.BooleanField(default=True, verbose_name='Active article'),
        ),
    ]
