# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_article_active_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryManufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category_man', models.CharField(max_length=50, verbose_name='Name category manufactures')),
                ('parent_category_man', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.CategoryManufactures', verbose_name='Parent category manufactures')),
            ],
            options={
                'db_table': 'category_manufactures',
            },
        ),
        migrations.AddField(
            model_name='manufactures',
            name='category_man',
            field=models.ManyToManyField(to='mysite.CategoryManufactures', verbose_name='Category manufactures'),
        ),
    ]
