# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20170518_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmenu',
            name='position_menu',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Position menu'),
        ),
    ]
