# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_navbarmenu_position_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarmenu',
            name='parent_menu',
        ),
        migrations.DeleteModel(
            name='NavbarMenu',
        ),
    ]
