# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20170529_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description_article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
