# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20170529_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Comments'),
        ),
    ]
