# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_article_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', ckeditor.fields.RichTextField(verbose_name='Comment')),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Article')),
            ],
            options={
                'db_table': 'comments_article',
            },
        ),
    ]
